services:
  nestjs_api_dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nestjs_api_dev
      - MYSQL_USER=nestjs_api_dev
      - MYSQL_PASSWORD=nestjs_api_dev
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./mysql:/var/lib/mysql
